seed_everything: 42
trainer:
  max_epochs: 50
model:
  lr: -1.0
  model_key: pytorch_resnet50
  output_features: 100
data:
  batch_size: 128
  data_dir: ~/ml_data/cifar-100
  data_loader_kwargs:
    num_workers: 8
