seed_everything: 42
trainer:
  logger: true
  max_epochs: 50
  log_every_n_steps: 20
model:
  lr: -1.0
  model_key: timm_mixer_b16_224_in21k
  output_features: 100
data:
  batch_size: 128
  data_dir: ~/ml_data/cifar-100
